### ISSUE TITLE
Video rotation on Web

### ISSUE THREAD

**Issue by d3rf** [AgoraIO/Basic-Video-Call#141]
I have a app made with flutter that is working fine. When I join in the channel with the flutter app I can see the stream on webpage without a problem, but the video rotation is landscape. I need rotate the stream video that comes from a flutter app and show on the webpage portrait
![2020-03-23 (2)](https://user-images.githubusercontent.com/9619501/77281276-62ba4680-6ca5-11ea-989a-4318e9237187.png)

**Comment by plutoless** [comment]
what parameters you have provided for setVideoEncoderConfiguration?
how is your phone positioned when above thing happens?

**Comment by phuphan1995** [comment]
I got the same problem with firefox. Please reopen this issue

**Comment by yoreland** [comment]
> I got the same problem with firefox. Please reopen this issue

From which device and SDK you publish the video stream?
Can you provide parameter for setVideoEncoderConfiguration for that?

**Comment by phuphan1995** [comment]
> > I got the same problem with firefox. Please reopen this issue
> 
> From which device and SDK you publish the video stream?
> Can you provide parameter for setVideoEncoderConfiguration for that?

I used react-native-agora for integrating Agora on mobile. It used agora.rtc:full-sdk:2.9.4 for android, AgoraRtcEngine_iOS", "2.9.1" for IOS and agora-rtc-sdk: ^3.1.0 on web. The video stream worked fine on Chrome but was rotated on Firefox. Config parameters are 
const config = {
  appid: '',
  channelProfile: 0,
  videoEncoderConfig: {
    width: width,
    height: height,
    bitrate: 1,
    frameRate: FPS30,
    orientationMode: Adaptative,
  },
  audioProfile: AudioProfileDefault,
  audioScenario: AudioScenarioDefault,
}.
Thanks for helping me

**Comment by plutoless** [comment]
in this case pls use portrait or landscape instead of adaptive

**Comment by leo8198** [comment]
Hello guys, I'm also facing the issue that @phuphan1995 described, but with few differences. Instead of React Native, I use flutter (basic call also made by @plutoless ) and when I open the web app in Firefox the image that came from the phone is rotated by 90 degrees. The image in the phone in the vertical turns in horizontal in the web app using Firefox. However, when I use Chrome this error doesn't occurs. I tried to configure the setVideoEncoderConfiguration but I don't know where to put the orientationMode in my code. I also searched in the documentation from Agora and nothing helped me. I will post my code from setVideoEncoderConfiguration. Thanks, guys.

`rtc.localStream.setVideoEncoderConfiguration({
            resolution: {
              width: 1280,
              height: 720,
            },
            frameRate: {
              min: 15,
              max: 30,
            },

          })`
